### PR TITLE
Lots of cleanup and minor improvements

### PR DESCRIPTION
**Pull request by hoijui**
* fixed compiler-warnings
* fixed CppCeck warnings
* added header includes (many were missing)
* fixed and improved the README
* cleanup white-spaces (EOL & EOF)

### CODE REVIEW

**Comment by eribertomota** [comment]
Hi @hoijui,

Thanks a lot for your changes and improvements. Can you add a Copyright line in head of each file changed by you?

There are some warnings when building. Would you like fix it?

Regards,

Eriberto

**Comment by hoijui** [comment]
:-)
I added the copyright notices.

I also made the CI script run through.
... did you reffer to any other warnings?

**Comment by eribertomota** [comment]
> :-)
> I added the copyright notices.
> 
> I also made the CI script run through.

Thanks! Yesterday the Ubuntu in GitHub was crashed and I didn't see any results.

> ... did you reffer to any other warnings?

Yes,

In Debian I can see:

```
pnm.c: In function ‘read_pnm’:
pnm.c:168:2: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
  168 |  fgets(magic, 10, fin);
      |  ^~~~~~~~~~~~~~~~~~~~~
pnm.c:174:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  174 |  fscanf(fin, "%d", &image->x);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
pnm.c:176:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  176 |  fscanf(fin, "%d", &image->y);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
pnm.c:178:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  178 |  fscanf(fin, "%d", &image->max);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pnm.c:210:4: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  210 |    fscanf(fin, "%d", &v);
      |    ^~~~~~~~~~~~~~~~~~~~~
pnm.c:220:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  220 |   fread(image->img, image->x * image->depth, image->y, fin);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

There are other warnings in CI test.

Thanks a lot for your work. I set you as "write" in repository. So you can commit directly, if you like it.

Is there a chance to remove embedded jpeglib and make the outguess depends of a shared lib?

Thanks again!

Cheers,

Eriberto

**Comment by hoijui** [comment]
thank you! :-)

honestly.. I don't even know why I started working on this project.. I will most likely never use it.. but it was like... a little child on the street, asking for food. ;-)

I might get to the warnings and the library, one of these days.

**Comment by eribertomota** [comment]
> thank you! :-)
> 
> honestly.. I don't even know why I started working on this project.. I will most likely never use it.. but it was like... a little child on the street, asking for food. ;-)
> 
> I might get to the warnings and the library, one of these days.

Don't worry. It is a puzzle. i also work over somethings that I don't use. Mainly packaging in Debian. Remember: you are a volunteer and you can to make what you want and if want.

Please, commit this PR when you want.

**Pull request merged**
